import "./globals.css";

import { GeistMono } from "geist/font/mono";
import Header from "../components/global-components/header";
import Footer from "../components/global-components/footer";
import SmoothScroll from "../providers/smooth-scroll";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={` ${GeistMono.variable} antialiased`}>
			<body>
				<SmoothScroll>
					<Header />
					{children}
					<Footer />
				</SmoothScroll>
			</body>
		</html>
	);
}
